use crate::{
    background_image::LoadedBackgroundImage,
    explorer::{ExplorerEntryKind, ExplorerOperationResult},
    explorer_tree_panel::ExplorerDirectoryEntries,
    file_history::LocalHistorySnapshot,
    image_preview::LoadedImagePreview,
    lsp_install::{LspInstallFailure, LspInstallOutcome, LspInstallStage},
    lsp_ui_events::LspUiEvent,
    persistence::PersistedSession,
    plugin_command_runtime::PluginCommandExecution,
    quick_open::{QuickOpenRankKey, QuickOpenResult},
    source_control_diff_runtime::{SourceControlDiffOpenOutcome, SourceControlDiffOpenRequest},
    source_control_patch_runtime::{SourceControlPatchCopyOutcome, SourceControlPatchCopyRequest},
    startup_arguments::StartupTarget,
    startup_tasks::GitScanRootCacheEntry,
    syntax::PluginSyntaxLoad,
    update_checker::{AvailableUpdate, UpdateCheckOutcome, UpdateInstallerReady},
    virtual_diff_runtime::{VirtualDiffOpenOutcome, VirtualDiffOpenRequest},
    virtual_revision_runtime::{VirtualRevisionOpenOutcome, VirtualRevisionOpenRequest},
};
use kuroya_core::{
    BufferId, Diagnostic, GitBlameLine, GitBranch, GitChangeStage, GitCommitSummary, GitDiffHunk,
    GitLineChangeKind, GitSnapshot, GitStashEntry, LspFoldingRange, PluginDescriptor,
    PluginDiscoveryError, ProjectIndex, SearchProgress, SearchResult, TextBuffer, WorkspaceTask,
};
use std::{
    collections::BTreeMap,
    path::PathBuf,
    sync::Arc,
    time::{Duration, SystemTime},
};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum SettingsFontTarget {
    Editor,
    Ui,
}

#[derive(Debug)]
pub(crate) enum UiEvent {
    CachedIndex {
        request_id: u64,
        root: PathBuf,
        index: ProjectIndex,
    },
    Indexed {
        request_id: u64,
        root: PathBuf,
        index: ProjectIndex,
    },
    FileLoaded {
        root: PathBuf,
        generation: u64,
        path: PathBuf,
        buffer: TextBuffer,
        elapsed: Duration,
        activate: bool,
        lossy: bool,
        binary: bool,
    },
    ImageFileLoaded {
        root: PathBuf,
        generation: u64,
        path: PathBuf,
        buffer: TextBuffer,
        preview: LoadedImagePreview,
        elapsed: Duration,
        activate: bool,
    },
    FileLoadFailed {
        root: PathBuf,
        generation: u64,
        path: PathBuf,
        error: String,
    },
    FileReloaded {
        root: PathBuf,
        generation: u64,
        request_id: u64,
        id: BufferId,
        path: PathBuf,
        buffer: TextBuffer,
        elapsed: Duration,
        version: u64,
        force_dirty: bool,
        lossy: bool,
        binary: bool,
    },
    ImageFileReloaded {
        root: PathBuf,
        generation: u64,
        request_id: u64,
        id: BufferId,
        path: PathBuf,
        buffer: TextBuffer,
        preview: LoadedImagePreview,
        elapsed: Duration,
        version: u64,
        force_dirty: bool,
    },
    FileReloadFailed {
        root: PathBuf,
        generation: u64,
        request_id: u64,
        id: BufferId,
        path: PathBuf,
        error: String,
        version: u64,
        force_dirty: bool,
    },
    FileSaved {
        root: PathBuf,
        generation: u64,
        id: BufferId,
        path: PathBuf,
        version: u64,
    },
    FileSaveFailed {
        root: PathBuf,
        generation: u64,
        id: BufferId,
        path: PathBuf,
        error: String,
    },
    LocalHistoryLoaded {
        root: PathBuf,
        generation: u64,
        path: PathBuf,
        snapshot_path: PathBuf,
        sequence: u128,
        text: String,
    },
    LocalHistoryFailed {
        root: PathBuf,
        generation: u64,
        path: PathBuf,
        error: String,
    },
    LocalHistoryBrowserLoaded {
        root: PathBuf,
        generation: u64,
        path: PathBuf,
        snapshots: Vec<LocalHistorySnapshot>,
    },
    LocalHistoryBrowserSnapshotLoaded {
        root: PathBuf,
        generation: u64,
        path: PathBuf,
        snapshot_path: PathBuf,
        sequence: u128,
        modified: Option<SystemTime>,
        result: Result<String, String>,
    },
    SessionSaved {
        root: PathBuf,
    },
    SessionSaveFailed {
        root: PathBuf,
        error: String,
    },
    OpenWorkspacePicked {
        request_id: u64,
        path: PathBuf,
    },
    OpenWorkspacePickerCanceled {
        request_id: u64,
    },
    OpenWorkspacePickerFailed {
        request_id: u64,
        error: String,
    },
    SettingsFontPicked {
        root: PathBuf,
        generation: u64,
        target: SettingsFontTarget,
        path: String,
    },
    SettingsFontPickerCanceled {
        root: PathBuf,
        generation: u64,
        target: SettingsFontTarget,
    },
    SettingsFontPickerFailed {
        root: PathBuf,
        generation: u64,
        target: SettingsFontTarget,
        error: String,
    },
    SettingsBackgroundImagePicked {
        root: PathBuf,
        generation: u64,
        path: String,
    },
    SettingsBackgroundImagePickerCanceled {
        root: PathBuf,
        generation: u64,
    },
    SettingsBackgroundImagePickerFailed {
        root: PathBuf,
        generation: u64,
        error: String,
    },
    EditorBackgroundImageLoaded {
        request_id: u64,
        path: PathBuf,
        loaded: LoadedBackgroundImage,
    },
    EditorBackgroundImageLoadFailed {
        request_id: u64,
        path: PathBuf,
        error: String,
    },
    ExplorerCreatePathPicked {
        root: PathBuf,
        generation: u64,
        kind: ExplorerEntryKind,
        path: PathBuf,
    },
    ExplorerCreatePathPickerCanceled {
        root: PathBuf,
        generation: u64,
        kind: ExplorerEntryKind,
    },
    ExplorerCreatePathPickerFailed {
        root: PathBuf,
        generation: u64,
        kind: ExplorerEntryKind,
        error: String,
    },
    ExplorerOperationFinished {
        root: PathBuf,
        generation: u64,
        operation: ExplorerOperationResult,
    },
    ExplorerOperationFailed {
        root: PathBuf,
        generation: u64,
        action: &'static str,
        path: PathBuf,
        error: String,
    },
    SearchFinished {
        request_id: u64,
        index_generation: u64,
        workspace_root: PathBuf,
        query: String,
        case_sensitive: bool,
        whole_word: bool,
        include_globs: Vec<String>,
        exclude_globs: Vec<String>,
        max_file_bytes: u64,
        max_results: usize,
        result: SearchResult,
    },
    SearchProgress {
        request_id: u64,
        index_generation: u64,
        workspace_root: PathBuf,
        query: String,
        case_sensitive: bool,
        whole_word: bool,
        include_globs: Vec<String>,
        exclude_globs: Vec<String>,
        max_file_bytes: u64,
        max_results: usize,
        progress: SearchProgress,
    },
    GitScanned {
        request_id: u64,
        root: PathBuf,
        scan_root: Option<PathBuf>,
        root_cache_entry: Option<GitScanRootCacheEntry>,
        git: GitSnapshot,
    },
    GitStageFinished {
        root: PathBuf,
        paths: Vec<PathBuf>,
    },
    GitStageFailed {
        root: PathBuf,
        paths: Vec<PathBuf>,
        error: String,
    },
    GitUnstageFinished {
        root: PathBuf,
        paths: Vec<PathBuf>,
    },
    GitUnstageFailed {
        root: PathBuf,
        paths: Vec<PathBuf>,
        error: String,
    },
    GitDiscardFinished {
        root: PathBuf,
        paths: Vec<PathBuf>,
    },
    GitDiscardFailed {
        root: PathBuf,
        paths: Vec<PathBuf>,
        error: String,
    },
    GitCommitFinished {
        request_id: u64,
        root: PathBuf,
        short_oid: String,
        message: String,
        smart_commit: bool,
    },
    GitCommitFailed {
        request_id: u64,
        root: PathBuf,
        error: String,
        smart_commit: bool,
    },
    GitBranchesLoaded {
        request_id: u64,
        root: PathBuf,
        operation_root: PathBuf,
        branches: Vec<GitBranch>,
    },
    GitBranchesFailed {
        request_id: u64,
        root: PathBuf,
        operation_root: PathBuf,
        error: String,
    },
    GitBranchSwitchFinished {
        request_id: u64,
        root: PathBuf,
        operation_root: PathBuf,
        branch: String,
    },
    GitBranchSwitchFailed {
        request_id: u64,
        root: PathBuf,
        operation_root: PathBuf,
        branch: String,
        error: String,
    },
    GitBranchCreateFinished {
        request_id: u64,
        root: PathBuf,
        operation_root: PathBuf,
        branch: String,
    },
    GitBranchCreateFailed {
        request_id: u64,
        root: PathBuf,
        operation_root: PathBuf,
        branch: String,
        error: String,
    },
    GitBranchDeleteFinished {
        root: PathBuf,
        operation_root: PathBuf,
        branch: String,
    },
    GitBranchDeleteFailed {
        root: PathBuf,
        operation_root: PathBuf,
        branch: String,
        error: String,
    },
    GitBranchRenameFinished {
        root: PathBuf,
        operation_root: PathBuf,
        old_branch: String,
        new_branch: String,
    },
    GitBranchRenameFailed {
        root: PathBuf,
        operation_root: PathBuf,
        old_branch: String,
        new_branch: String,
        error: String,
    },
    GitHistoryLoaded {
        request_id: u64,
        limit: usize,
        root: PathBuf,
        operation_root: PathBuf,
        commits: Vec<GitCommitSummary>,
    },
    GitHistoryFailed {
        request_id: u64,
        limit: usize,
        root: PathBuf,
        operation_root: PathBuf,
        error: String,
    },
    GitBlameLoaded {
        request_id: u64,
        root: PathBuf,
        operation_root: PathBuf,
        path: PathBuf,
        lines: Vec<GitBlameLine>,
        text: String,
    },
    GitBlameFailed {
        request_id: u64,
        root: PathBuf,
        operation_root: PathBuf,
        path: PathBuf,
        error: String,
    },
    GitStashesLoaded {
        request_id: u64,
        root: PathBuf,
        operation_root: PathBuf,
        stashes: Vec<GitStashEntry>,
    },
    GitStashesFailed {
        request_id: u64,
        root: PathBuf,
        operation_root: PathBuf,
        error: String,
    },
    GitStashSaved {
        root: PathBuf,
        operation_root: PathBuf,
        short_oid: String,
    },
    GitStashSaveFailed {
        root: PathBuf,
        operation_root: PathBuf,
        error: String,
    },
    GitStashApplied {
        root: PathBuf,
        operation_root: PathBuf,
        index: usize,
    },
    GitStashApplyFailed {
        root: PathBuf,
        operation_root: PathBuf,
        index: usize,
        error: String,
    },
    GitStashPopped {
        root: PathBuf,
        operation_root: PathBuf,
        index: usize,
    },
    GitStashPopFailed {
        root: PathBuf,
        operation_root: PathBuf,
        index: usize,
        error: String,
    },
    GitStashDropped {
        root: PathBuf,
        operation_root: PathBuf,
        index: usize,
    },
    GitStashDropFailed {
        root: PathBuf,
        operation_root: PathBuf,
        index: usize,
        error: String,
    },
    GitHunksLoaded {
        request_id: u64,
        root: PathBuf,
        operation_root: PathBuf,
        path: PathBuf,
        stage: GitChangeStage,
        hunks: Vec<GitDiffHunk>,
    },
    GitHunksFailed {
        request_id: u64,
        root: PathBuf,
        operation_root: PathBuf,
        path: PathBuf,
        stage: GitChangeStage,
        error: String,
    },
    GitHunkStaged {
        root: PathBuf,
        path: PathBuf,
        hunk_index: usize,
    },
    GitHunkStageFailed {
        root: PathBuf,
        path: PathBuf,
        hunk_index: usize,
        error: String,
    },
    GitHunkUnstaged {
        root: PathBuf,
        path: PathBuf,
        hunk_index: usize,
    },
    GitHunkUnstageFailed {
        root: PathBuf,
        path: PathBuf,
        hunk_index: usize,
        error: String,
    },
    GitHunkDiscarded {
        root: PathBuf,
        path: PathBuf,
        hunk_index: usize,
        text: String,
        expected_buffer: Option<(BufferId, u64)>,
    },
    GitHunkDiscardFailed {
        root: PathBuf,
        path: PathBuf,
        hunk_index: usize,
        error: String,
    },
    GitPatchCopyFinished {
        root: PathBuf,
        operation_root: PathBuf,
        generation: u64,
        request_id: u64,
        request: SourceControlPatchCopyRequest,
        result: Result<SourceControlPatchCopyOutcome, String>,
    },
    SourceControlDiffOpenFinished {
        root: PathBuf,
        operation_root: PathBuf,
        generation: u64,
        request_id: u64,
        request: SourceControlDiffOpenRequest,
        result: Result<SourceControlDiffOpenOutcome, String>,
    },
    VirtualDiffOpenFinished {
        root: PathBuf,
        generation: u64,
        request_id: u64,
        request: VirtualDiffOpenRequest,
        result: Result<VirtualDiffOpenOutcome, String>,
    },
    VirtualRevisionOpenFinished {
        root: PathBuf,
        generation: u64,
        request_id: u64,
        request: VirtualRevisionOpenRequest,
        result: Result<VirtualRevisionOpenOutcome, String>,
    },
    FallbackFoldingRangesLoaded {
        id: BufferId,
        path: PathBuf,
        version: u64,
        ranges: Vec<LspFoldingRange>,
    },
    EditorDiffLinesComputed {
        root: PathBuf,
        id: BufferId,
        path: PathBuf,
        version: u64,
        ignore_trim_whitespace: bool,
        lines: BTreeMap<usize, GitLineChangeKind>,
    },
    WorkspaceTasksLoaded {
        request_id: u64,
        root: PathBuf,
        tasks: Vec<WorkspaceTask>,
    },
    WorkspaceTasksFailed {
        request_id: u64,
        root: PathBuf,
        error: String,
    },
    WorkspacePluginsLoaded {
        request_id: u64,
        root: PathBuf,
        plugins: Vec<PluginDescriptor>,
        errors: Vec<PluginDiscoveryError>,
        syntax_load: PluginSyntaxLoad,
    },
    WorkspacePluginsFailed {
        request_id: u64,
        root: PathBuf,
        error: String,
    },
    PluginCommandFinished {
        root: PathBuf,
        generation: u64,
        plugin_id: String,
        command_id: String,
        result: Result<PluginCommandExecution, String>,
    },
    PluginOpenFileRequested {
        plugin_id: String,
        path: PathBuf,
    },

    PluginBufferTextApply {
        plugin_id: String,
        path: PathBuf,
        text: String,
    },
    DiagnosticsComputed {
        request_id: u64,
        id: BufferId,
        path: PathBuf,
        version: u64,
        diagnostics: Vec<Diagnostic>,
    },
    QuickOpenRanked {
        request_id: u64,
        key: Arc<QuickOpenRankKey>,
        results: Vec<QuickOpenResult>,
    },
    ExplorerDirectoryLoaded {
        root: PathBuf,
        generation: u64,
        request_token: u64,
        directory: PathBuf,
        snapshot: ExplorerDirectoryEntries,
    },
    UpdateCheckFinished(UpdateCheckOutcome),
    UpdateCheckFailed {
        error: String,
    },
    UpdateInstallerReady(UpdateInstallerReady),
    UpdateDownloadProgress {
        latest_version: String,
        asset_name: String,
        bytes_downloaded: u64,
    },
    UpdateDownloadFailed {
        available: AvailableUpdate,
        error: String,
    },

    StartupSessionLoaded {
        root: PathBuf,
        target: Option<StartupTarget>,
        session: Option<Box<PersistedSession>>,
        warning: Option<String>,
    },
    LspInstallProgress {
        language: String,
        display_name: String,
        stage: LspInstallStage,
    },
    LspInstallFinished {
        language: String,
        display_name: String,
        result: Result<LspInstallOutcome, LspInstallFailure>,
    },
    Lsp(LspUiEvent),
}
