id = "lua"
display_name = "lua-language-server"
languages = ["lua"]
asset = "lsp-lua-language-server-{platform}"
launch = "lua-language-server"
install = "repo"

[verify]
command = "lua-language-server"
args = ["--version"]
